# Generated by Django 4.2 on 2023-05-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_usercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('C', 'COMMON_PEOPLE'), ('T', 'TOUR_LEADER'), ('O', 'ORGANIZATION')], max_length=1, null=True),
        ),
    ]
