# Generated by Django 4.2.1 on 2023-07-06 07:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_org', models.CharField(max_length=200, null=True, unique=True)),
                ('description', models.TextField(null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('Phone', models.CharField(max_length=20, null=True)),
                ('rates', models.IntegerField(blank=True, default=0, null=True)),
                ('wallet', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('gender', models.BooleanField(null=True)),
                ('bio', models.TextField(null=True)),
                ('registration_date', models.DateField(auto_now=True, null=True)),
                ('profile_image', models.TextField(blank=True, null=True)),
                ('wallet', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
                ('national_code', models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid national code.')])),
                ('phone', models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{1,3}[- ]?\\d{3,4}[- ]?\\d{4}$', 'Enter a valid phone number.')])),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_choice', models.CharField(choices=[('A', 'accept'), ('R', 'reject'), ('W', 'wait')], default='W', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rate_Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Rate_Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_transport', models.CharField(choices=[('A', 'airplane'), ('S', 'ship'), ('B', 'bus'), ('T', 'train')], max_length=1, null=True)),
                ('return_transport', models.CharField(choices=[('A', 'airplane'), ('S', 'ship'), ('B', 'bus'), ('T', 'train')], max_length=1, null=True)),
                ('departure_date', models.DateTimeField(null=True)),
                ('return_date', models.DateTimeField(null=True)),
                ('Description', models.TextField(null=True)),
                ('capacity', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('Price', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(5000)])),
                ('image', models.TextField(null=True)),
                ('hotel_name', models.CharField(max_length=30, null=True)),
                ('destination_city', models.ManyToManyField(related_name='cities', to='Profile.city')),
                ('destination_country', models.ManyToManyField(related_name='countries', to='Profile.country')),
                ('organization_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Profile.organization')),
                ('origin_city_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Profile.city')),
                ('place_ids', models.ManyToManyField(blank=True, to='Place.place')),
            ],
        ),
        migrations.CreateModel(
            name='CommenPeople',
            fields=[
                ('Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Profile.person')),
            ],
        ),
        migrations.CreateModel(
            name='TourLeader',
            fields=[
                ('person_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Profile.person')),
                ('rates', models.IntegerField(blank=True, default=0, null=True)),
                ('rate_no', models.IntegerField(blank=True, default=0, null=True)),
                ('joindDate', models.DateTimeField(auto_now=True, null=True)),
                ('phonetl', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='trip_common_people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orga_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='Profile.organization')),
            ],
        ),
    ]
