# Generated by Django 4.2.1 on 2023-05-19 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.city'),
        ),
        migrations.AddField(
            model_name='organization',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.country'),
        ),
        migrations.AddField(
            model_name='trip',
            name='TourLeader_ids',
            field=models.ManyToManyField(blank=True, to='Profile.tourleader'),
        ),
        migrations.AddField(
            model_name='tourleader',
            name='orga_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.organization'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='common_people_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.commenpeople'),
        ),
        migrations.AddField(
            model_name='commenpeople',
            name='friend_id',
            field=models.ManyToManyField(to='Profile.commenpeople'),
        ),
    ]
