# Generated by Django 4.2.1 on 2023-05-17 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourleader',
            name='rate',
        ),
        migrations.AlterField(
            model_name='tourleader',
            name='orga_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourleader', to='Profile.organization'),
        ),
    ]
