# Generated by Django 4.2 on 2023-04-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0002_alter_person_bio_alter_person_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="image",
            field=models.TextField(null=True),
        ),
    ]
