# Generated by Django 4.2.1 on 2023-05-19 06:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='user_id',
            new_name='person_id',
        ),
        migrations.RenameField(
            model_name='tourleader',
            old_name='Id',
            new_name='person_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='rate_no',
        ),
        migrations.RemoveField(
            model_name='tourleader',
            name='rate',
        ),
        migrations.AddField(
            model_name='organization',
            name='rates',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tourleader',
            name='joindDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tourleader',
            name='phonetl',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tourleader',
            name='rate_no',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tourleader',
            name='rates',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourleader',
            name='orga_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourleader', to='Profile.organization'),
        ),
        migrations.CreateModel(
            name='Rate_Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('tour_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_tour', to='Profile.tourleader')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_tour', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rate_Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('orgg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_org', to='Profile.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_org', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
