# Generated by Django 4.2 on 2023-05-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='common_people_id',
            field=models.ManyToManyField(blank=True, to='Profile.commenpeople'),
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='registration_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourleader',
            name='joindDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourleader',
            name='rate_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tourleader',
            name='rates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
