# Generated by Django 4.2 on 2023-06-07 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_trip_common_people_id_trip_hotel_name_trip_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_choice', models.CharField(choices=[('A', 'accept'), ('R', 'reject'), ('W', 'wait')], default='W', max_length=1)),
                ('common_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.commenpeople')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.organization')),
            ],
        ),
    ]
