# Generated by Django 4.2 on 2023-04-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_remove_person_first_name_remove_person_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='origin',
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='begin_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
