# Generated by Django 4.2 on 2023-06-23 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_trip_common_people_id_trip_hotel_name_trip_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='rates',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rate_org',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
