# Generated by Django 4.2 on 2023-06-26 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_alter_organization_rates_alter_rate_org_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='rates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='PremiumRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_choice', models.CharField(choices=[('A', 'accept'), ('R', 'reject'), ('W', 'wait')], default='W', max_length=1)),
                ('common_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.commenpeople')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.organization')),
            ],
            options={
                'unique_together': {('organization', 'common_people')},
            },
        ),
    ]
