# Generated by Django 4.2 on 2023-06-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_premiumrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenpeople',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='premiumrequest',
            unique_together={('organization', 'common_people')},
        ),
    ]
