# Generated by Django 4.2 on 2023-07-04 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_organization_wallet_person_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='national_code',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid national code.')]),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{1,3}[- ]?\\d{3,4}[- ]?\\d{4}$', 'Enter a valid phone number.')]),
        ),
    ]
