# Generated by Django 4.2 on 2023-07-04 13:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.db import connections

# def transfer_data(apps, schema_editor):
#     # MyOldIntermediateModel = apps.get_model('yourappname', 'MyOldIntermediateModel')
#     # MyNewIntermediateModel = apps.get_model('yourappname', 'MyNewIntermediateModel')

#     # for old_obj in MyOldIntermediateModel.objects.all():
#     #     MyNewIntermediateModel.objects.create(
#     #         mymodel1=old_obj.mymodel1,
#     #         mymodel2=old_obj.mymodel2,
#     #         extra_field='default_value'  # Set the default value for the new field
#     #     )
#     with connections['default'].cursor() as cursor:
#         cursor.execute('SELECT id, trip_id , commenpeople_id FROM Profile_trip_common_people_id')

#         for id, trip_id , commenpeople_id in cursor.fetchall():
#             cursor.execute('INSERT INTO Profile_trip_common_people (id, trip_id , commenpeople_id , count) VALUES (%s, %s, %s , %s)', [id, trip_id , commenpeople_id , 1])
class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_person_national_code_person_phone'),
    ]

    operations = [ 
        migrations.CreateModel(
            name='trip_common_people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(django.core.validators.MinValueValidator(1))),
                ('trip', models.ForeignKey(on_delete=models.CASCADE, to='Profile.Trip')),
                ('common_people', models.ForeignKey(on_delete=models.CASCADE, to='Profile.CommenPeople')),
            ],
            options={
                'unique_together': {('trip', 'common_people')},
            },
        ),       
        # migrations.RunPython(transfer_data),

        migrations.RemoveField(
            model_name="Trip",
            name="common_people_id"
        ),     
        migrations.AddField(
            model_name="Trip",
            name="common_people_id",
            field=models.ManyToManyField(to='Profile.CommenPeople', through='Profile.trip_common_people' , blank = True)
        )
        
    ]
