# Generated by Django 4.2 on 2023-05-15 20:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Place', '0006_alter_place_rate'),
        ('Profile', '0008_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='Id',
        ),
        migrations.RemoveField(
            model_name='tourleader',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tourleader',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='Tour_leader_id',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='destination_city',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='destination_country',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='image',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='origin_city',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='origin_country',
        ),
        migrations.AddField(
            model_name='organization',
            name='Address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='Phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.city'),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_org',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='rate_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourleader',
            name='rate',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='trip',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='Price',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='trip',
            name='TourLeader_ids',
            field=models.ManyToManyField(null=True, to='Profile.tourleader'),
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_transport',
            field=models.CharField(choices=[('A', 'airplane'), ('S', 'ship'), ('B', 'bus'), ('T', 'train')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Profile.country'),
        ),
        migrations.AddField(
            model_name='trip',
            name='place_ids',
            field=models.ManyToManyField(null=True, to='Place.place'),
        ),
        migrations.AddField(
            model_name='trip',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='return_transport',
            field=models.CharField(choices=[('A', 'airplane'), ('S', 'ship'), ('B', 'bus'), ('T', 'train')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='capacity',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
