# Generated by Django 4.2 on 2023-07-07 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('national_code', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid national code.')])),
                ('phone', models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{1,3}[- ]?\\d{3,4}[- ]?\\d{4}$', 'Enter a valid phone number.')])),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='passenger',
            field=models.ManyToManyField(blank=True, to='Profile.passenger'),
        ),
    ]
