# Generated by Django 4.2 on 2023-05-16 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0006_alter_place_rate'),
        ('Profile', '0009_remove_organization_id_remove_tourleader_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='begin_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='origin_country_id',
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_city',
            field=models.ManyToManyField(related_name='cities', to='Profile.city'),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_country',
            field=models.ManyToManyField(related_name='countries', to='Profile.country'),
        ),
        migrations.AddField(
            model_name='trip',
            name='organization_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Profile.organization'),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Profile.city'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='TourLeader_ids',
            field=models.ManyToManyField(blank=True, to='Profile.tourleader'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='place_ids',
            field=models.ManyToManyField(blank=True, to='Place.place'),
        ),
    ]
