# Generated by Django 4.2 on 2023-05-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_remove_trip_begin_time_remove_trip_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='common_people_id',
            field=models.ManyToManyField(blank=True, to='Profile.commenpeople'),
        ),
    ]
