# Generated by Django 4.2 on 2023-05-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_trip_common_people_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='hotel_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
