# Generated by Django 4.2 on 2023-11-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0013_alter_tourleader_orga_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linux_type', models.CharField(max_length=255, null=True)),
                ('processore_model', models.CharField(max_length=255, null=True)),
                ('date_time', models.DateTimeField(auto_now=True, null=True)),
                ('hard_space', models.FloatField(null=True)),
            ],
        ),
    ]
