# Generated by Django 4.2 on 2023-04-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
