# Generated by Django 4.2 on 2023-05-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='comment_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='rate_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
