# Generated by Django 4.2.1 on 2023-05-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0003_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=5, max_digits=2),
        ),
        migrations.AddField(
            model_name='place',
            name='rate_no',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
