# Generated by Django 4.2 on 2023-07-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0004_alter_rate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
