# Generated by Django 4.2 on 2023-05-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0005_alter_place_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2),
        ),
    ]
