# Generated by Django 4.2 on 2023-04-17 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('gender', models.BooleanField(null=True)),
                ('bio', models.TextField(null=True)),
                ('registration_date', models.DateField(auto_now=True)),
                ('profile_image', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=30)),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TourLeader',
            fields=[
                ('Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Profile.person')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Post_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.TextField(blank=True, null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='trip_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.trip'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.person')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='Tour_leader_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.tourleader'),
        ),
        migrations.AddField(
            model_name='tourleader',
            name='orga_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.organization'),
        ),
        migrations.CreateModel(
            name='CommenPeople',
            fields=[
                ('Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Profile.person')),
                ('friend_id', models.ManyToManyField(to='Profile.commenpeople')),
            ],
        ),
    ]