# Generated by Django 4.2 on 2023-04-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_person_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
    ]
