# Generated by Django 4.2 on 2023-04-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_country_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(null=True, upload_to='profile/imaged'),
        ),
    ]
