# Generated by Django 4.2 on 2023-04-22 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_alter_city_country_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.TextField(null=True)),
                ('common_people_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.commenpeople')),
            ],
        ),
    ]
